language: ruby
cache: bundler
gemfile: fixture/gemfile

rvm:
  - 2.2.6
  - 2.3.3
  - 2.6.7
  - 2.7.3

env:
  - CHEF_VERSION=master EXPECTED_FILE=README-expected.md METADATA=metadata.rb
  - CHEF_VERSION=12.6.0 EXPECTED_FILE=README-expected.md METADATA=metadata.rb
  - CHEF_VERSION=12.5.1 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=12.4.1 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=12.3.0 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=12.2.1 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=12.1.2 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=12.0.3 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=11.18.12 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=11.16.4 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=11.14.6 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=11.12.8 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
  - CHEF_VERSION=11.10.4 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb

matrix:
  fast_finish: true
  exclude:
    - env: CHEF_VERSION=11.12.8 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
      rvm: 2.3.3
    - env: CHEF_VERSION=11.10.4 EXPECTED_FILE=README-expected_legacy.md METADATA=metadata_legacy.rb
      rvm: 2.3.3
    - env: CHEF_VERSION=master EXPECTED_FILE=README-expected.md METADATA=metadata.rb
      rvm: 2.2.6
    - env: CHEF_VERSION=master EXPECTED_FILE=README-expected.md METADATA=metadata.rb
      rvm: 2.3.3
    - env: CHEF_VERSION=master EXPECTED_FILE=README-expected.md METADATA=metadata.rb
      rvm: 2.6.7

  allow_failures:
    - env: CHEF_VERSION=master EXPECTED_FILE=README-expected.md METADATA=metadata.rb

script:
  - cd fixture
  - bundle exec knife cookbook doc . -o README-generated.md -c knife.rb --metadata $METADATA
  - diff $EXPECTED_FILE README-generated.md && rm README-generated.md
